[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "rekki-testkit"
version = "0.0.1a"
description = "Rekki Testkit"
authors = [{ name = "Lanqing Huang", email = "lqhuang@typef.io" }]
requires-python = ">=3.13"
license = { text = "Apache-2.0" }
readme = "README.md"
