from __future__ import annotations


class StateT: ...


class ContextT:
    async def self_ref(self): ...

    async def props(self): ...

    async def sender(self): ...

    async def children(self): ...

    async def parent(self): ...

    async def system(self): ...
